FROM node:9

ARG PROXY_URL
RUN npm set registry ${PROXY_URL:-http://192.168.0.24:4873}

WORKDIR /moviewatcher/moviewatcher-server
ADD ./moviewatcher-server/package.json .
RUN npm install

EXPOSE 3000
CMD ["npm", "run", "debug"]